.Dd Juny 18, 2005
.Dt ACR-RECOVER 1
.Os
.Sh NAME
.Nm acr-recover
.Nd acr recover utility
.Sh SYNOPSYS
.Nm acr-recover
.Op Ar configure-script
.Sh DESCRIPTION
.Pp
acr-recover is a reverse engineering tool for acr. The objective of this
tool is to allow developers to recover part or entire configure.acr file
from a generated configure script.
.Pp
This is an experimental tool. Results may not be exact. Don't have
backward compatibility (at least <0.4).
.Pp
acr-recover is also accessible from the acr command using the -r flag.
.Sh SEE ALSO
.Xr amr 1
.Xr acr 1
.Xr configure.acr 5
.Sh AUTHOR
Written by pancake <pancake@phreaker.net>
.Pp
http://www.nopcode.org/?t=acr
