.Dd Aug 12, 2022
.Dt ACR-CAT 1
.Os
.Sh NAME
.Nm acr-cat
.Nd acr cat utility
.Sh SYNOPSIS
.Nm acr-cat
.Op Ar configure-script
.Sh DESCRIPTION
acr-cat is a recovery tool for acr. The objective of this tool is
to allow developers to cat part or entire configure.acr file from
a generated configure script.
.Pp
This is an experimental tool. Results may not be exact. Don't have
backward compatibility (at least <0.4).
.Pp
acr-cat is also accessible from the acr command using the \-r flag.
.Sh SEE ALSO
.Xr amr 1
.Xr acr 1
.Xr acr-wrap 1
.Xr configure.acr 5
.Sh AUTHOR
Written by pancake <pancake@nopcode.org>
