#!/bin/sh
# convert meson wrap files into makefiles for compatibility reasons
F="$1"
if [ -z "$F" ]; then
	echo "Usage: acr-wrap foo.wrap > foo.mk"
	exit 1
fi
(
NAME=""
while : ; do
	read LINE
	[ $? != 0 ] && break
	echo "$LINE" | grep -q =
	if [ $? = 0 ]; then
		if [ -z "${NAME}" ]; then
			echo "malformed"
			break
		fi
		LINE=`echo "$LINE"|sed -e 's, ,,g'`
		echo "WRAP_${NAME}_${LINE}" | sed -e 's/=/:=/g'
		eval "export WRAP_${LINE}"
	else
		echo "$LINE" | grep -q '^\['
		if [ $? = 0 ]; then
			NAME=$(echo "$LINE" |sed -e 's,-,_,g' -e 's,\[,,g' -e 's,\],,g')
		fi
	fi
done

cat <<EOF

all: ${WRAP_directory}
	@echo "Nothing to do"

${WRAP_directory}:
EOF

GIT_FLAGS=""
if [ -n "${WRAP_depth}" ]; then
	GIT_FLAGS="--depth=${WRAP_depth}"
fi
echo "${NAME}" | grep -q -- '_git'
if [ $? = 0 ]; then
	echo "	git clone ${GIT_FLAGS} ${WRAP_url} ${WRAP_directory}"
else
	echo "	echo Not supported && exit 1"
fi
if [ -n "$WRAP_revision" ]; then
	echo "	cd ${WRAP_directory} && git reset --hard ${WRAP_revision}"
fi
if [ -n "$WRAP_patch_directory" ]; then
	echo "	cp -f ${WRAP_patch_directory}/* ${WRAP_directory}"
fi

cat <<EOF

clean:
	rm -rf ${WRAP_directory}
EOF

) < $F
