# This is a basic workflow that is manually triggered

name: ci

on: push

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
# on:
#   workflow_dispatch:
#     # Inputs the workflow accepts.
#     inputs:
#       name:
#         # Friendly description to be shown in the UI instead of 'name'
#         description: 'Build and test'
#         # Default value if no value is explicitly provided
#         default: 'ACR'
#         # Input has to be provided for the workflow to run
#         required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Clone
      run: cd .. ; rm -rf acr ; git clone https://github.com/radare/acr ; cd acr
    - name: Configure
      run: ./configure --prefix=/usr
    - name: Build and install
      run: make ; sudo make install
    - name: Run tests
      run: make -C tests
    - name: Regenerate
      run: sh autogen.sh
    - name: Debian
      run: make -C dist
    - name: Pub
      uses: actions/upload-artifact@v4
      with:
        path: dist/acr/*.deb
